-- =====================================================================
-- 01_reference.sql : dimension and reference tables
-- Depends on: 00_init.sql
-- =====================================================================
SET search_path TO parkitup, public;

-- ---------------------------------------------------------------------
-- dim_city
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_city (
    city_id         SMALLINT     PRIMARY KEY,
    city_name       TEXT         NOT NULL UNIQUE,
    state_name      TEXT         NOT NULL,
    ncr_zone        TEXT         NOT NULL
                    CHECK (ncr_zone IN ('Central NCR','South NCR','East NCR',
                                        'West NCR','North NCR')),
    is_core_delhi   BOOLEAN      NOT NULL DEFAULT FALSE
);

COMMENT ON TABLE dim_city IS
  'PROVENANCE: public. Administrative reference data for the Delhi NCR study area.';
COMMENT ON COLUMN dim_city.ncr_zone IS
  'Analyst-assigned NCR sub-region used for market roll-ups. Not an official designation.';

-- ---------------------------------------------------------------------
-- dim_locality
-- The locality is the unit of MARKET analysis. Business questions 1-3 and 14
-- are answered at this grain, so it must be a first-class dimension rather
-- than a text column on parking_lots.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_locality (
    locality_id             SMALLINT   PRIMARY KEY,
    city_id                 SMALLINT   NOT NULL
                            REFERENCES dim_city (city_id),
    locality_name           TEXT       NOT NULL,
    micro_market_type       TEXT       NOT NULL
                            CHECK (micro_market_type IN (
                                'CBD','Commercial','Retail High Street',
                                'IT/Office Park','Residential','Transit Hub',
                                'Hospital/Institutional','Mixed Use')),
    has_metro_station       BOOLEAN    NOT NULL,
    metro_line_count        SMALLINT   NOT NULL DEFAULT 0
                            CHECK (metro_line_count >= 0 AND metro_line_count <= 6),
    population_density_band TEXT       NOT NULL
                            CHECK (population_density_band IN
                                   ('Low','Medium','High','Very High')),
    record_source           TEXT       NOT NULL
                            CHECK (record_source IN ('public_osm','public_curated')),
    CONSTRAINT uq_locality_per_city UNIQUE (city_id, locality_name),
    -- A locality cannot claim metro lines without a metro station.
    CONSTRAINT ck_locality_metro_consistent
        CHECK ( (has_metro_station AND metro_line_count >= 1)
             OR (NOT has_metro_station AND metro_line_count = 0) )
);

COMMENT ON TABLE dim_locality IS
  'PROVENANCE: public (OpenStreetMap + curated desk research). The unit of '
  'market-level analysis. Populated in the data pipeline.';
COMMENT ON COLUMN dim_locality.micro_market_type IS
  'Dominant land-use character. Drives demand-pattern expectations (office '
  'parks peak on weekdays, retail on weekends).';

-- ---------------------------------------------------------------------
-- dim_date
-- DATE is used directly as the primary key. A surrogate integer date key adds
-- no value here and makes ad-hoc SQL harder to read.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_date (
    activity_date       DATE      PRIMARY KEY,
    day_of_week         SMALLINT  NOT NULL
                        CHECK (day_of_week BETWEEN 1 AND 7),   -- 1 = Monday (ISO)
    day_name            TEXT      NOT NULL,
    is_weekend          BOOLEAN   NOT NULL,
    is_public_holiday   BOOLEAN   NOT NULL DEFAULT FALSE,
    month_num           SMALLINT  NOT NULL CHECK (month_num BETWEEN 1 AND 12),
    month_name          TEXT      NOT NULL,
    quarter_num         SMALLINT  NOT NULL CHECK (quarter_num BETWEEN 1 AND 4),
    year_num            SMALLINT  NOT NULL,
    iso_week            SMALLINT  NOT NULL CHECK (iso_week BETWEEN 1 AND 53),
    -- Generated so day_type can never drift out of sync with its inputs.
    day_type            TEXT      GENERATED ALWAYS AS (
                            CASE WHEN is_public_holiday THEN 'Holiday'
                                 WHEN is_weekend        THEN 'Weekend'
                                 ELSE 'Weekday' END ) STORED
);

COMMENT ON TABLE dim_date IS
  'PROVENANCE: public/deterministic. Calendar dimension covering the '
  'simulated observation window. Generated by database/seeds/.';
COMMENT ON COLUMN dim_date.day_type IS
  'Generated column. Holiday takes precedence over Weekend, which takes '
  'precedence over Weekday. Used to join fact_lot_hourly_profile.';

-- ---------------------------------------------------------------------
-- dim_funnel_stage
-- A strictly ordered ladder of BD pipeline stages. Loss REASONS are not
-- stages: they live on outreach.lost_reason. Mixing the two would make
-- stage_order meaningless and break funnel drop-off analysis.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_funnel_stage (
    stage_id        SMALLINT  PRIMARY KEY,
    stage_code      TEXT      NOT NULL UNIQUE,
    stage_name      TEXT      NOT NULL,
    stage_order     SMALLINT  NOT NULL UNIQUE
                    CHECK (stage_order >= 1),
    is_success_stage BOOLEAN  NOT NULL DEFAULT FALSE,
    stage_description TEXT    NOT NULL
);

COMMENT ON TABLE dim_funnel_stage IS
  'PROVENANCE: synthetic/config. Ordered BD funnel ladder. Seeded in the schema layer '
  'because the scoring and funnel framework depends on it.';

-- ---------------------------------------------------------------------
-- dim_score_dimension
-- The five scoring pillars, as data rather than as hard-coded strings.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dim_score_dimension (
    dimension_code  TEXT      PRIMARY KEY
                    CHECK (dimension_code IN ('DEMAND','REVENUE','COMPETITION',
                                              'STRATEGIC_FIT','FEASIBILITY')),
    dimension_name  TEXT      NOT NULL UNIQUE,
    pillar_group    TEXT      NOT NULL
                    CHECK (pillar_group IN ('Attractiveness','Feasibility')),
    description     TEXT      NOT NULL,
    display_order   SMALLINT  NOT NULL UNIQUE
);

COMMENT ON TABLE dim_score_dimension IS
  'PROVENANCE: config. The five scoring pillars. pillar_group splits the '
  'score into the two axes of the Acquisition Matrix: how attractive the '
  'opportunity is, versus how realistically it can be closed.';
COMMENT ON COLUMN dim_score_dimension.pillar_group IS
  'Attractiveness = DEMAND, REVENUE, COMPETITION, STRATEGIC_FIT. '
  'Feasibility = FEASIBILITY. Used as the X/Y axes on dashboard page 3.';

-- ---------------------------------------------------------------------
-- data_lineage
-- Column-level provenance register. Row-level record_source values identify
-- where an entity came from; this table answers the different question of
-- where each attribute came from. That distinction matters for mixed rows,
-- such as an OSM parking coordinate with a synthetic tariff.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS data_lineage (
    table_name       TEXT  NOT NULL,
    column_name      TEXT  NOT NULL,
    lineage_type     TEXT  NOT NULL
                     CHECK (lineage_type IN
                            ('PUBLIC','DERIVED','SYNTHETIC','ASSUMED','CONFIG')),
    source_name      TEXT  NOT NULL,
    source_reference TEXT,
    methodology_note TEXT  NOT NULL,
    business_purpose TEXT  NOT NULL,
    CONSTRAINT pk_data_lineage PRIMARY KEY (table_name, column_name)
);

COMMENT ON TABLE data_lineage IS
  'PROVENANCE: config. Field-level register distinguishing PUBLIC, DERIVED, '
  'SYNTHETIC, ASSUMED and CONFIG values across the source data layer.';
